Permissions readme
CodelyTV/pr-size-labeler pull request #80
Opened 2024-07-23 17:27 UTC by Achllle

## What type of PR is this? (check all applicable)

- [x] Documentation Update

## Description

- Adds the required permissions to the README for this to work at all.
- Notes for those using forks

## Notes to Reviewer

I've made some other minor improvements, including specifying the full version in the README's action.yml example. With the current `v1`, some of the features described in the same readme do not work. Happy to replace that with a note specifying people should consider using the latest version.

## Link to issues addressed

- closes #47
- closes #8

2024-07-25 13:31 UTC, JavierCane commented
Nice one @Achllle! Thanks a lot for the contribution 😊

I've given some feedback and suggested changes. Please review them when you get a chance 🙌

2024-07-25 13:32 UTC, JavierCane requested changes
Nice one @Achllle! Thanks a lot for the contribution 😊

I've given some feedback and suggested changes. Please review them when you get a chance 🙌

2024-07-25 19:31 UTC, Achllle commented on README.md
> +      - uses: codelytv/pr-size-labeler@v1.10.0
Sounds good, I'll revert my commit.

2024-07-25 19:34 UTC, Achllle commented on README.md
> +**note**: When using forks and where you don't want any PR to be able to execute code, replace `on: [pull_request]` with `on: [pull_request_target]` (see [GitHub docs](https://docs.github.com/en/acti
I should've seen this, thanks. Done manually since your suggestion contained a typo.

2024-07-26 06:38 UTC, JavierCane approved these changes
Thanks for reviewing the suggestions. Merging! 😊

2024-07-26 06:39 UTC, merged